### ISSUE TITLE
[Feature] Export C bindings for using jsonte as a library

### ISSUE THREAD

**Issue by stirante** [MCDevKit/jsonte#1]
**Overview**

Create a file, that would contain bindings, which would be later compiled with cgo, so C/C++ or Java through JNI could use jsonte as a library without hurdle of starting the CLI every time.

**Tasks**
 - [ ] Create file with bindings (like `bindings.go`)
 - [ ] Adjust GitHub Action, to compile properly
 - [ ] Include libraries for all platforms in release
 - [ ] Test it with a sample application
